version: 2
updates:
- package-ecosystem: maven
  directory: "/patch-diff-report-tool"
  schedule:
    interval: weekly
    day: "friday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: dependency
- package-ecosystem: maven
  directory: "/releasenotes-builder"
  schedule:
    interval: weekly
    day: "friday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: dependency
