---
# Nginx

nginx_extra_http_options: |
  ignore_invalid_headers off;
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_max_temp_file_size 0;
  proxy_connect_timeout 90;
  proxy_send_timeout 90;
  proxy_read_timeout 90;
  proxy_request_buffering off;

nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    root: "/var/cache/jenkins/war"
    access_log: "/var/log/nginx/jenkins_access.log"
    error_log: "/var/log/nginx/jenkins_error.log"
    state: "present"
    filename: "jenkins.conf"
    extra_parameters: |
      location / {
        sendfile off;
        proxy_pass         http://127.0.0.1:8080;
      }
